# conda environment configuration for mybinder
name: mybinder-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - python=3.9
  - cartopy
  - gdal
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - numpy
  - owslib
  - pandas
  - plotly
  - tabulate
  - pip
  - pip:
    - matplotlib
    - owslib
    - pandas
    - tabulate