site_name: MSC Open Data / <br>Données ouvertes du SMC

# name of the remote set in your fork where the documentation will actually be deployed
# validate value with `git remote -v`, it must be pointing to http://github.com/eccc-msc/open-data.git
remote_name: github

# Related documentation: https://www.mkdocs.org/user-guide/configuration/#remote_branch

nav:
    - Available data / <br>Données disponibles: msc-data/readme_en.md
    - Data access / <br>Accès aux données:
        - MSC Datamart / <br>Datamart du SMC: msc-datamart/readme_en.md
        - MSC GeoMet / <br>GeoMet du SMC: msc-geomet/readme_en.md
        - Cost-recovered services /<br>Services à recouvrement de coûts: cost-recovered/readme_en.md
    - Usage overview / <br>Aperçu de l'utilisation: usage/readme_en.md
    - Contact us / <br>Contactez-nous: https://weather.gc.ca/mainmenu/contact_us_e.html

theme:
    name: mkdocs
    custom_dir: custom_theme/
